### ISSUE TITLE
[ Support Question ] The value for inverse... is invalid

### ISSUE THREAD

**Issue by light24bulbs** [genie-team/graphql-genie#19] opened 2019-02-11 08:06 UTC
Can you help me figure out what this error means?
```
      "message": "The value for \"inverse\" on \"post\" in type \"Comment\" is invalid, the inversely related field must define its inverse as \"post\".",
```
My schema looks like this:
```gql
type Comment {
  id: ID! @unique
  createdAt: DateTime @createdTimestamp
  updatedAt: DateTime @updatedTimestamp
  author: User @relation(name: "commentsByUser")
  body: String
  post: Post @relation(name: "commentsOnPost")
}

enum postType {
  TEXT
  LINK
}

type Post {
  id: ID! @unique
  createdAt: DateTime @createdTimestamp
  updatedAt: DateTime @updatedTimestamp
  author: User @relation(name: "postsByUser")
  type: postType
  comments: [Comment!] @relation(name: "commentsOnPost")
}

type User {
  id: ID! @unique
  createdAt: DateTime @createdTimestamp
  updatedAt: DateTime @updatedTimestamp
  userName: String! @unique
  posts: [Post!] @relation(name: "postsByUser")
  comments: [Comment!] @relation(name: "commentsByUser")
}
```
Am I not defining my relations correctly?

**Comment by acoreyj** [comment] 2019-02-21 19:07
Hmm it doesn't look like you are doing anything wrong, I'll take a look and see what the issue may be

**Comment by light24bulbs** [comment] 2019-02-21 20:14
Here is a repo for reproduction if you get the chance.  Currently I have all the `@relations` commented out to get it working, but once they are uncommented it throws.  

Also, if you're in there poking around, I think the template strings and seperate merged schema files make for a clean structure (assuming it works).  Maybe if you like it I could PR something similar into the examples

**Comment by warwickgrigg** [comment] 2019-02-25 10:11
I'm also getting "The value for inverse... is invalid" but my workaround is to change the name of a field. Steps to reproduce: 

1. paste this minimal schema into the [genie playground] (https://genie-team.github.io/graphql-genie-client/) and save it

`type Person {
  id: ID! @unique
  name: String!
  devices: [Device!]
  bugReports: [BugReport!]
}

type Device {
  id: ID! @unique
  hostname: String!
  person: Person
}

type BugReport {
  id: ID! @unique
  summary: String!
  person: Person
}`

2 Paste this query and execute it:

`{
  devices {
    id
  }
}`

3. Error message is

`The value for \"inverse\" on \"bugReports\" in type \"Person\" is invalid, the inversely related field must define its inverse as \"bugReports\"."`

My workaround is to change the name of the "person" field in "bugReport" to "raisedBy" . Relation directives don't seem to make any difference to the outcome.

**Comment by darmie** [comment] 2019-03-06 11:46
I am getting this issue too. Please how do we resolve?

**Comment by daliwali** [comment] 2019-03-07 02:28
Hi. Chiming in here because I wrote this error message. I think it is perfectly clear what it means and how to address the issue, but it is opaque to users of this because `inverse` isn't explicitly defined here.

@acoreyj inverse field needs to be defined on both sides of a relationship for now. I could relax this requirement by trying to automatically assign it if one side is assigned, I just thought it was more explicit this way.

**Comment by darmie** [comment] 2019-03-07 06:54
@daliwali even the examples are failing.  Since this project was inspired by prisma.  It would be nice if it accepts relationships same way prisma does. 

I am trying to use genie as an offline alternative of prisma to cache large data in IndexedDB

**Comment by daliwali** [comment] 2019-03-07 07:24
@darmie there is the option to not specify an inverse like how prisma does it. that's up to @acoreyj

**Comment by darmie** [comment] 2019-03-07 07:31
@acoreyj I am really looking forward to a solution right now.  I would appreciate if this issue is resolved soon.

**Comment by light24bulbs** [comment] 2019-03-07 08:20
@daliwali I think this is a legit bug and maybe not pilot error, since the examples are failing.  Time to take a closer look?

**Comment by daliwali** [comment] 2019-03-07 08:33
Here's the check: https://github.com/fortunejs/fortune/blob/169edd5b8b0ba6de08f1049e843e4c7afe7c170b/lib/record_type/ensure_types.js#L46-L50
Here's the test case: https://github.com/fortunejs/fortune/blob/d14401b4d328eb98681dbd0db15f16f2114ba2ea/test/unit/record_type.js#L170-L177

It is an issue with graphql-genie.

**Comment by acoreyj** [comment] 2019-03-07 16:18
Thanks for the help guys, looking into this today

**Comment by acoreyj** [comment] 2019-03-07 21:18
@light24bulbs  @warwickgrigg 
Hey all this is now fixed in the latest version. 

The issue was a bug where if multiple types had a relation to the same other type and had the same field name it would setup the inverses wrong for one of them.

So since `comments: [Comment!]` was on 2 different types it was incorrectly computing the inverse for one of them, causing the error to be thrown by Fortune.

**Closed** 2019-03-07 21:18 UTC

**Comment by darmie** [comment] 2019-03-07 21:20
Thank you @acoreyj if we pull the latest version for NPM, this issue will be fixed?

**Comment by acoreyj** [comment] 2019-03-07 22:04
@darmie that is correct, anything >= .0.4.20
