### ISSUE TITLE
Default export not working for plugins

### ISSUE THREAD

**Issue by ecwyne** [genie-team/graphql-genie#5] opened 2018-08-10 16:56 UTC
```typescript
import auth from 'graphql-genie-authentication'; // undefined
import subs from 'graphql-genie-subscriptions'; // undefined

import * as auth from 'graphql-genie-authentication';  // [Function: authentication]
import * as subs from 'graphql-genie-subscriptions'; // [Function: subscriptions]
```

I think this has something to do with the rollup configuration (from what I can tell)

**Comment by ecwyne** [comment] 2018-08-10 17:00
And I get the following TS error when I use the `import * as` syntax.

```
[ts] Cannot invoke an expression whose type lacks a call signature. Type 'typeof import("graphql-genie-subscriptions")' has no compatible call signatures.
```

**Comment by ecwyne** [comment] 2018-08-10 17:09
I started looking into https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/package.json as a template to see how they set things up to work both with node/ts and browser

**Comment by acoreyj** [comment] 2018-08-10 19:46
Hmm not sure what would be causing the undefined, do you know what you might be doing differently from the [indexeddb example](https://github.com/genie-team/graphql-genie/tree/master/examples/indexeddb) or the [memory example](https://github.com/genie-team/graphql-genie/tree/master/examples/memory) as it works there.

Maybe something in your compiler options could fix it? Let me know what you find or more details to reproduce because it's definitely possible something is being exported incorrectly.

**Comment by ecwyne** [comment] 2018-08-10 20:14
It looks like all of the examples are using either webpack/rollup with `awesome-typescript-loader` while I'm using `tsc` directly?

Looks like the examples are using `module: 'es2015'` in `tsconfig.json` and then using webpack/rollup to take care of the es2015 imports/exports.

If I switch to `module: 'commonjs'` I get `TypeError: graphql_genie_subscriptions_1.default is not a function`

**Comment by acoreyj** [comment] 2018-08-10 21:04
Yea, it does seem to be something with how typescript creating a commonjs module handles imports but I'm not sure why. Rollup does seem to ditch the `default` of the export when it creates the bundles, not sure if that's something intentional or not. 

A workaround for now would be getting typescript to compile with the * import so it doesn't add the .default in the result.
```ts

import * as auth from 'graphql-genie-authentication';  // [Function: authentication]
import * as subs from 'graphql-genie-subscriptions'; // [Function: subscriptions]

const subplugin = <any>subs;
genie.use(subplugin(new PubSub()));

```

**Comment by ecwyne** [comment] 2018-08-10 21:07
That's a better workaround than the one I'd been using.

```typescript
genie.use(
    require('graphql-genie-authentication')('USER', 'USER', 'OWNER', 'ADMIN'),
);
```

**Comment by acoreyj** [comment] 2018-08-11 02:48
This should be fixed in the latest versions of the plugins.

For subscriptions I took out the rollout step and just use the typescript compile as there are no internal dependencies.

For auth I finally figured out setting the exports to named in rollup allowed it to keep the default export.

**Closed** 2018-08-11 02:48 UTC
